language: en
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: EmbeddingIntentClassifier
- name: ResponseSelector
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
