language: en
pipeline: 
- name: "supervised_embeddings"
- name: "WhitespaceTokenizer"
- name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"
- name: "ResponseSelector"
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
